### ISSUE TITLE
Adjust keyboard and gamepad bindings

### ISSUE THREAD

**Issue by VideogameScrapbook** [Double-Fine-Game-Club/pongball#115]
When I started the latest build, I assumed that the arrow keys or WASD would control Player 1 (as they had in previous builds). Since this wasn't working, I assumed that the controls might be broken. @Cheeseness told me through IRC that Y and H are the current controls for player 1.

Unless there is a good reason to keep the left player controls as Y/H, I'd recommend changing it to W/S (since a lot of games use WASD for movement). Furthermore, I think the action buttons for the left player should be Left Shift and Left Ctrl.

As for the right player, I'd recommend arrow keys/Right Shift/Right Ctrl. This would mirror the other players controls and most closely align with other games. These controls would also allow for either one handed or two handed play, depending on preference.

And if InputManager actually allows this: when there is only one player per computer (such as online or single player offline), then either W/S or up/down could be used for the player's paddle (since up/down is the most intuitive for people who might skip the instructions quickly).

I don't want to step on anybody's toes, so I won't make these changes myself. 

@Cheeseness also mentioned that the gamepad bindings also may need some tweaking, but I haven't yet tested the gamepad option myself.

**Comment by fragmental** [comment]
They're yh because using left shift, left ctrl, left at with yh is uncomfortable.

**Comment by fragmental** [comment]
Ideally 2 players on one keyboard would use 2 hands.

**Comment by fragmental** [comment]
I don't know how to edit comments on phone. Should have read using one hand on wd and one hand on left shift/alt/ctrl is uncomfortable

**Comment by VideogameScrapbook** [comment]
Here's my suggestion after some thought: Up/Down/Right Shift/Right Ctrl for right player. W/S/Left Shift/Left Ctrl for left player, Besides being symmetrical and more likely to be discovered based on similar mappings in other games, this would allow either player to use 1 or 2 hands for their controls. 

I don't want to step on anybody's toes so I've I will update the description according to these ideas rather than make the changes myself. But I believe my suggestion isn't any less comfortable than the current setup.

And if InputManager actually allows this: when there is only one player per computer (such as online or single player offline), then either W/S or up/down could be used for the player's paddle (since up/down is the most intuitive for people who might skip the instructions quickly).

**Comment by VideogameScrapbook** [comment]
@Cheeseness, @lightsoda, @fragmental, what do you think of my suggestion in the comment above?

**Comment by fragmental** [comment]
Have you tried using WS  and left shift/ctrl/alt with two hands for more
than just a few seconds?  Your hands have to overlap and it's awkward, in
my experience.  I do agree that WS is a more obvious choice for left player
because it is so commonly used, but I don't know if it can be comfortably
used.

Up Down right shift/ctrl/alt should be right player mappings now unless
someone has purposefully or mistakenly changed them.  Right player should
also be first player, unless that has changed.

**Comment by VideogameScrapbook** [comment]
@fragmental, yes, I tested with two hands for about a minute (please note that my proposal doesn't require using the Alt keys at all, which makes a huge difference). With my keyboard and keeping my left hand close to the left edge of the Shift button, it feels good, but I know that hands and keyboards vary. I noticed somebody did a pull request that changed controls a bit but not quite to what I proposed. In the end I think everybody could have a different opinion about optimum controls and it just depends on what @Cheeseness decides to do regarding the pull requests.

**Comment by fragmental** [comment]
possibly.  There are the power buttons and the flipper buttons.  Which is 3 or 4?

**Comment by Cheeseness** [comment]
I'm comfortable using WS and left shift/ctrl/alt with two hands and don't have any problems.

Different keyboards, hand sizes and finger preferences, and whether a player is sitting in them middle or to the left of the keyboard are all definitely going to have an impact here - I think anybody offering feedback *must* have had two people sitting at their keyboard for that feedback to be relevant (otherwise we're likely to be getting experiences from people sitting in the middle of the keyboard clouding things up).

Right now, first player is left player, and the right player's power controls are space and left alt.

**Comment by Cheeseness** [comment]
I'm still getting around to reviewing pull requests. I'll see how #122 looks when testing.

**Comment by fragmental** [comment]
As for first player left, if no one intentionally changed that, then I did
it by mistake when I was working on the UI.  If I did it, it's a simple
change, and can be done by changing the order of the paddle spawn prefab in
the load assets script in the unity (profiler, is that what it's called?
I'm afk).  But that's only IF I changed it.

Hopefully, at some point we can overhaul inputs and handle them in-game,
making them easier to remap for the player, but unity doesn't make that
easy, so that will probably have to be post AF stuff.

**Comment by fragmental** [comment]
Not to bring up a dead issue, but I tried and you were correct, w/s is more comfortable when you're left of the keyboard.  Absolutely 100%

Seems like a good reason to make first player right side, though, since middle of the keyboard would be the natural sitting position of a single player.  Possibly trifling detail? *shrug*

**Comment by Cheeseness** [comment]
I've popped up some changes in #129 that address legitimate bugs that came in with the first implementation, and tries to address some of the comfort/awkwardness concerns laid out here.

**Comment by Cheeseness** [comment]
#129 has been merged. I'll close this one here, and we can open new issues (referencing this and others if needed) to address any further refinements/changes that are needed.
